import type { Project } from "@/libs/projects";
import {
  buildPaddleEnvFile,
  getEffectivePaddlePlans,
} from "@/libs/paddle-plans";
import { inferPaddleEnvFromClientToken } from "@/libs/paddle-setup-plans";
import { buildResendFromEmail } from "@/libs/resend-domain";

export type ProjectEnvEntry = {
  key: string;
  value: string;
  secret?: boolean;
  section: string;
  ready: boolean;
  hint?: string;
};

export type ProjectEnvFile = {
  entries: ProjectEnvEntry[];
  missingSections: string[];
  content: string;
};

function pushEntry(
  entries: ProjectEnvEntry[],
  section: string,
  key: string,
  value: string | null | undefined,
  options?: { secret?: boolean; hint?: string; placeholder?: string }
) {
  const trimmed = value?.trim() ?? "";
  entries.push({
    key,
    value: trimmed || options?.placeholder || "",
    secret: options?.secret,
    section,
    ready: Boolean(trimmed),
    hint: options?.hint,
  });
}

export function buildProjectEnvEntries(project: Project): ProjectEnvEntry[] {
  const entries: ProjectEnvEntry[] = [];
  const slug = project.slug;

  pushEntry(entries, "App", "NEXT_PUBLIC_SITE_URL", process.env.NEXT_PUBLIC_SITE_URL, {
    placeholder: "http://localhost:3000",
    hint: "Local dev URL or production domain.",
  });
  pushEntry(entries, "Auth", "NEXTAUTH_URL", process.env.NEXTAUTH_URL, {
    placeholder: "http://localhost:3000",
  });
  pushEntry(entries, "Auth", "NEXTAUTH_SECRET", process.env.NEXTAUTH_SECRET, {
    secret: true,
    placeholder: "generate-a-random-32-char-secret",
    hint: "Run openssl rand -base64 32",
  });

  const supabaseUrl =
    project.supabase_project_url ??
    (project.supabase_project_ref ? `https://${project.supabase_project_ref}.supabase.co` : null);

  pushEntry(entries, "Supabase", "NEXT_PUBLIC_SUPABASE_URL", supabaseUrl);
  pushEntry(entries, "Supabase", "NEXT_PUBLIC_SUPABASE_ANON_KEY", project.supabase_anon_key, {
    secret: true,
  });
  pushEntry(entries, "Supabase", "SUPABASE_SERVICE_ROLE_KEY", project.supabase_service_role_key, {
    secret: true,
    hint: "Server-only — never expose in the browser.",
  });

  pushEntry(entries, "Google OAuth", "GOOGLE_CLIENT_ID", project.google_oauth_client_id);
  pushEntry(entries, "Google OAuth", "GOOGLE_CLIENT_SECRET", project.google_oauth_client_secret, {
    secret: true,
  });

  const resendFrom =
    project.resend_from_name && project.resend_domain
      ? buildResendFromEmail(project.resend_from_name, project.resend_domain)
      : null;

  pushEntry(entries, "Resend", "RESEND_API_KEY", null, {
    secret: true,
    placeholder: "re_...",
    hint: "From Resend dashboard → API Keys (after connecting in Integrations).",
  });
  pushEntry(entries, "Resend", "RESEND_FROM_EMAIL", resendFrom, {
    hint: project.resend_domain_added ? undefined : "Complete step 5 to generate the from address.",
  });

  if (project.paddle_provisioned && project.paddle_client_token) {
    const paddleEnv = inferPaddleEnvFromClientToken(project.paddle_client_token);
    const plans = getEffectivePaddlePlans(project.paddle_plans).filter((plan) => plan.priceId);

    const paddleBlock = buildPaddleEnvFile({
      env: paddleEnv,
      clientToken: project.paddle_client_token,
      apiKey: project.paddle_api_key,
      webhookSecret: project.paddle_webhook_secret,
      plans,
    });

    for (const line of paddleBlock.split("\n")) {
      if (!line.trim() || line.startsWith("#")) continue;
      const eq = line.indexOf("=");
      if (eq <= 0) continue;
      const key = line.slice(0, eq);
      const value = line.slice(eq + 1);
      pushEntry(entries, "Paddle", key, value, {
        secret: key.includes("SECRET") || key.includes("API_KEY"),
      });
    }
  } else {
    pushEntry(entries, "Paddle", "NEXT_PUBLIC_PADDLE_ENV", "sandbox");
    pushEntry(entries, "Paddle", "NEXT_PUBLIC_PADDLE_CLIENT_TOKEN", null, {
      placeholder: "Complete step 6 (Payments)",
    });
    pushEntry(entries, "Paddle", "PADDLE_API_KEY", null, { secret: true });
    pushEntry(entries, "Paddle", "PADDLE_WEBHOOK_SECRET", null, { secret: true });
  }

  pushEntry(entries, "Optional", "NEXT_PUBLIC_GA_MEASUREMENT_ID", null, {
    placeholder: "G-XXXXXXXXXX",
    hint: `Add after step 9 (Analytics) for ${slug}.`,
  });

  return entries;
}

export function buildProjectEnvFile(project: Project): ProjectEnvFile {
  const entries = buildProjectEnvEntries(project);

  const sections = ["Supabase", "Google OAuth", "Resend", "Paddle"] as const;
  const missingSections = sections.filter((section) => {
    const sectionEntries = entries.filter((entry) => entry.section === section);
    return sectionEntries.length > 0 && sectionEntries.every((entry) => !entry.ready);
  });

  const lines: string[] = [`# ${project.name} — .env.local`, `# Generated by ShipNow setup guide`, ""];

  let currentSection = "";
  for (const entry of entries) {
    if (entry.section !== currentSection) {
      if (currentSection) lines.push("");
      currentSection = entry.section;
      lines.push(`# ${entry.section}`);
    }
    if (entry.hint && !entry.ready) {
      lines.push(`# ${entry.hint}`);
    }
    lines.push(`${entry.key}=${entry.value}`);
  }

  lines.push("");
  return {
    entries,
    missingSections,
    content: lines.join("\n"),
  };
}

export function countReadyEnvEntries(project: Project): { ready: number; total: number } {
  const entries = buildProjectEnvEntries(project).filter(
    (entry) => !entry.key.startsWith("NEXT_PUBLIC_GA")
  );
  const ready = entries.filter((entry) => entry.ready).length;
  return { ready, total: entries.length };
}
