/** Resolving icons for analytics breakdowns.
 *
 *  The sets live in `public/analytics/` and are generated by
 *  `scripts/build-analytics-icons.mjs`. The manifest is imported rather than
 *  the directory being read at request time, so an unknown label resolves to
 *  the fallback without touching the filesystem.
 *
 *  Every label here originates from a parsed user agent or a CDN geo header,
 *  so it is attacker-shaped input. Nothing is interpolated into a path until
 *  it has been matched against the manifest. */

import manifest from "@/public/analytics/manifest.json";

const BROWSER_FALLBACK = "/analytics/browsers/_fallback.svg";
const FLAG_FALLBACK = "/analytics/flags/_fallback.svg";

const BROWSERS = new Set(manifest.browsers);
const FLAGS = new Set(manifest.flags);

/** Icon for a browser name as produced by `parseUserAgent`.
 *
 *  Microsoft Edge and Samsung Internet resolve to the fallback: simple-icons
 *  removed those marks, and drawing a lookalike would misrepresent a trademark
 *  rather than identify it. */
export function browserIcon(browser: string | null | undefined): string {
  if (!browser) return BROWSER_FALLBACK;

  const slug = browser.toLowerCase().replace(/\s+/g, "-");

  return BROWSERS.has(slug) ? `/analytics/browsers/${slug}.svg` : BROWSER_FALLBACK;
}

/** Flag for an ISO 3166-1 alpha-2 country code. */
export function flagIcon(country: string | null | undefined): string {
  if (!country) return FLAG_FALLBACK;

  const code = country.toLowerCase();
  if (!/^[a-z]{2}$/.test(code)) return FLAG_FALLBACK;

  return FLAGS.has(code) ? `/analytics/flags/${code}.svg` : FLAG_FALLBACK;
}

/** Readable country name for a code.
 *
 *  `Intl.DisplayNames` is built in, so this needs no lookup table to maintain
 *  and stays correct as territories change. Falls back to the raw code, which
 *  is still more useful than nothing. */
export function countryName(country: string | null | undefined): string {
  if (!country) return "—";

  try {
    const display = new Intl.DisplayNames(["en"], { type: "region" });
    return display.of(country.toUpperCase()) ?? country;
  } catch {
    return country;
  }
}
